/api/auth/admin         /.netlify/functions/auth-admin      200
/api/auth/employee      /.netlify/functions/auth-employee   200
/api/auth/visit         /.netlify/functions/auth-visit      200
/api/auth/logout        /.netlify/functions/auth-logout     200
/api/state/import       /.netlify/functions/state-import    200
/api/state              /.netlify/functions/state           200
/api/team               /.netlify/functions/team-list       200
/api/bistrosoft/status  /.netlify/functions/bistro-status   200
/api/bistrosoft/sales   /.netlify/functions/bistro-sales    200
/api/bistrosoft/months  /.netlify/functions/bistro-months   200
